### ISSUE TITLE
Read access error involving incorrectly named ROM

### ISSUE THREAD

**Issue by sweetsbeats** [nenechi-fan-club/CHIP-8-emu#2]
When you give chip8 a directory with a non-existent file, the program will read random memory and crash.
We should look into ROM existence assurance.

**Comment by s-varezhkin** [comment]
Added `is_open()` check when loading ROM in 6a0a8b1c79bd78ee9a5d4e8063da05aebeab6731

**Comment by sweetsbeats** [comment]
Tested and CHIP8.exe crashes after logging error in loading ROM, but no RAE.
Since the read access error is fixed, we'll close this issue for now.
