### ISSUE TITLE
Abnormal GPU usage when rendering

### ISSUE THREAD

**Issue by s-varezhkin** [nenechi-fan-club/CHIP-8-emu#3]

**Comment by sweetsbeats** [comment]
The reason GPU usage is so high, is because SDL_UpdateTexture is an extremely slow function, as noted on the [documentation page](https://wiki.libsdl.org/SDL_UpdateTexture).
The fix for GPU usage would be to implement this with SDL_LockTexture.

**Comment by s-varezhkin** [comment]
Can you look into current Lock/Unlock implementation in the comment section.

**Comment by sweetsbeats** [comment]
So I've implemented texture streaming inside the graphics::update_texture() method and GPU usage has dropped significantly(on my machine it dropped from 45-50% to around 14-15%).
I monitored usage of CPU, RAM, and GPU usage and nothing seems to be leaking or eating resources, so I think it's safe to say we've closed the case.
