### ISSUE TITLE
High framerate and graphical glitches when upscaling texture

### ISSUE THREAD

**Issue by s-varezhkin** [nenechi-fan-club/CHIP-8-emu#5]
Framerate is much higher when streaming to 64x32 texture and upscaling it compared to old upscaling method. Also, depending on ROM some graphical glitches might be present.

**Comment by sweetsbeats** [comment]
Most likely has to do with line 47 of graphics.cpp, you seem to be re-initializing the SDL_Rect every render call. Easiest solution is to make an SDL_Rect* private member, initialize the size once (probably around construction) and later on add a method to resize.

**Comment by s-varezhkin** [comment]
Making SDL_Rect private member doesn't seem to fix either issue.

**Comment by s-varezhkin** [comment]
Framerate issue was related to setting delay value in `SDL_Delay` and glitches were fixed in ff3b5fe5f2552742027c72d65f9bc6caa2678adf.
Issue will be closed for now but because new rendering method is potentially less secure, we should either look into any potential backdoors in drawing instruction or find bug in the old code.
